ERROR: 
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 141, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/routes/login.py", line 15, in Login
    raise Exception("TEST")
Exception: TEST
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 143, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/base/pages.py", line 14, in Index
    print(id(self.sio))
AttributeError: 'PageMaker' object has no attribute 'sio'
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 143, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/base/pages.py", line 14, in Index
    print(id(self.sio))
AttributeError: 'PageMaker' object has no attribute 'sio'
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 143, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/base/pages.py", line 14, in Index
    print(id(self.sio))
AttributeError: 'PageMaker' object has no attribute 'sio'
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 143, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/base/pages.py", line 14, in Index
    print(id(self.sio))
AttributeError: 'PageMaker' object has no attribute 'sio'
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 143, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/base/pages.py", line 14, in Index
    print(id(self.sio))
AttributeError: 'PageMaker' object has no attribute 'sio'
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 143, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/base/pages.py", line 14, in Index
    print(id(self.sio))
AttributeError: 'PageMaker' object has no attribute 'sio'
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 143, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/base/pages.py", line 14, in Index
    print(id(self.sio))
AttributeError: 'PageMaker' object has no attribute 'sio'
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 143, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/base/pages.py", line 14, in Index
    print(id(self.sio))
AttributeError: 'PageMaker' object has no attribute 'sio'
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 143, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/base/pages.py", line 14, in Index
    print(id(self.sio))
AttributeError: 'PageMaker' object has no attribute 'sio'
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 143, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/base/pages.py", line 14, in Index
    print(id(self.sio))
AttributeError: 'PageMaker' object has no attribute 'sio'
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 143, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/base/pages.py", line 14, in Index
    print(id(self.sio))
AttributeError: 'PageMaker' object has no attribute 'sio'
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 143, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/base/pages.py", line 14, in Index
    print(id(self.sio))
AttributeError: 'PageMaker' object has no attribute 'sio'
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 143, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/base/pages.py", line 14, in Index
    print(id(self.sio))
AttributeError: 'PageMaker' object has no attribute 'sio'
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 143, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/base/pages.py", line 14, in Index
    print(id(self.sio))
AttributeError: 'PageMaker' object has no attribute 'sio'
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 143, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/base/pages.py", line 14, in Index
    print(id(self.sio))
AttributeError: 'PageMaker' object has no attribute 'sio'
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 143, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/base/pages.py", line 19, in Index
    q()
NameError: name 'q' is not defined
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 143, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/base/pages.py", line 19, in Index
    q()
NameError: name 'q' is not defined
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 143, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/base/pages.py", line 19, in Index
    q()
NameError: name 'q' is not defined
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 143, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/base/pages.py", line 15, in magic
    return f()
TypeError: Index() missing 1 required positional argument: 'self'
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 143, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/base/pages.py", line 15, in magic
    return f()
TypeError: Index() missing 1 required positional argument: 'self'
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 143, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/base/pages.py", line 15, in magic
    return f()
TypeError: Index() missing 1 required positional argument: 'self'
