ERROR: 
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 141, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/routes/login.py", line 15, in Login
    raise Exception("TEST")
Exception: TEST
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 143, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/base/pages.py", line 14, in Index
    print(id(self.sio))
AttributeError: 'PageMaker' object has no attribute 'sio'
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 143, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/base/pages.py", line 14, in Index
    print(id(self.sio))
AttributeError: 'PageMaker' object has no attribute 'sio'
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 143, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/base/pages.py", line 14, in Index
    print(id(self.sio))
AttributeError: 'PageMaker' object has no attribute 'sio'
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 143, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/base/pages.py", line 14, in Index
    print(id(self.sio))
AttributeError: 'PageMaker' object has no attribute 'sio'
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 143, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/base/pages.py", line 14, in Index
    print(id(self.sio))
AttributeError: 'PageMaker' object has no attribute 'sio'
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 143, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/base/pages.py", line 14, in Index
    print(id(self.sio))
AttributeError: 'PageMaker' object has no attribute 'sio'
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 143, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/base/pages.py", line 14, in Index
    print(id(self.sio))
AttributeError: 'PageMaker' object has no attribute 'sio'
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 143, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/base/pages.py", line 14, in Index
    print(id(self.sio))
AttributeError: 'PageMaker' object has no attribute 'sio'
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 143, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/base/pages.py", line 14, in Index
    print(id(self.sio))
AttributeError: 'PageMaker' object has no attribute 'sio'
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 143, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/base/pages.py", line 14, in Index
    print(id(self.sio))
AttributeError: 'PageMaker' object has no attribute 'sio'
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 143, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/base/pages.py", line 14, in Index
    print(id(self.sio))
AttributeError: 'PageMaker' object has no attribute 'sio'
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 143, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/base/pages.py", line 14, in Index
    print(id(self.sio))
AttributeError: 'PageMaker' object has no attribute 'sio'
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 143, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/base/pages.py", line 14, in Index
    print(id(self.sio))
AttributeError: 'PageMaker' object has no attribute 'sio'
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 143, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/base/pages.py", line 14, in Index
    print(id(self.sio))
AttributeError: 'PageMaker' object has no attribute 'sio'
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 143, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/base/pages.py", line 14, in Index
    print(id(self.sio))
AttributeError: 'PageMaker' object has no attribute 'sio'
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 143, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/base/pages.py", line 19, in Index
    q()
NameError: name 'q' is not defined
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 143, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/base/pages.py", line 19, in Index
    q()
NameError: name 'q' is not defined
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 143, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/base/pages.py", line 19, in Index
    q()
NameError: name 'q' is not defined
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 143, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/base/pages.py", line 15, in magic
    return f()
TypeError: Index() missing 1 required positional argument: 'self'
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 143, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/base/pages.py", line 15, in magic
    return f()
TypeError: Index() missing 1 required positional argument: 'self'
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 143, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/base/pages.py", line 15, in magic
    return f()
TypeError: Index() missing 1 required positional argument: 'self'
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 229, in get_response
    return getattr(page_maker, method)(*args)
AttributeError: 'PageMaker' object has no attribute 'StringEscaping'
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 228, in get_response
    return getattr(page_maker, method)(*args)
AttributeError: 'PageMaker' object has no attribute 'StringEscaping'
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 228, in get_response
    method, args, hostargs = self.router(path, method, host)
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 116, in request_router
    for pattern, handler, routemethod, hostpattern in req_routes:
ValueError: too many values to unpack (expected 4)
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 238, in get_response
    return getattr(page_maker, method)(*args)
TypeError: Index() takes 1 positional argument but 2 were given
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 238, in get_response
    return getattr(page_maker, method)(*args)
AttributeError: 'PageMaker' object has no attribute '/'
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 238, in get_response
    return getattr(page_maker, method)(*args)
AttributeError: 'PageMaker' object has no attribute '/'
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 239, in get_response
    return getattr(page_maker, method)(*args)
TypeError: Index() takes 1 positional argument but 2 were given
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 239, in get_response
    return getattr(page_maker, method)(*args)
AttributeError: 'PageMaker' object has no attribute '/'
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 239, in get_response
    return getattr(page_maker, method)(*args)
AttributeError: 'PageMaker' object has no attribute '/'
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 238, in get_response
    return getattr(page_maker, method)(*args)
TypeError: Index() takes 1 positional argument but 2 were given
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 238, in get_response
    return getattr(page_maker, method)(*args)
AttributeError: 'PageMaker' object has no attribute '/'
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 238, in get_response
    return getattr(page_maker, method)(*args)
AttributeError: 'PageMaker' object has no attribute '/'
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 236, in get_response
    method, args, hostargs = self.router(path, method, host)
ValueError: too many values to unpack (expected 3)
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 237, in get_response
    method, args, hostargs, test = self.router(path, method, host)
NameError: name 'path' is not defined
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 237, in get_response
    method, args, hostargs, test = self.router(path, method, host)
NameError: name 'path' is not defined
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 237, in get_response
    method, args, hostargs, test = self.router(path, method, host)
NameError: name 'path' is not defined
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 237, in get_response
    method, args, hostargs, test = self.router(path, method, host)
NameError: name 'path' is not defined
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 237, in get_response
    method, args, hostargs, test = self.router(path, method, host)
NameError: name 'path' is not defined
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 237, in get_response
    method, args, hostargs, test = self.router(path, method, host)
NameError: name 'path' is not defined
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 237, in get_response
    method, args, hostargs, test = self.router(path, method, host)
NameError: name 'path' is not defined
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 237, in get_response
    method, args, hostargs, test = self.router(path, method, host)
NameError: name 'path' is not defined
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 237, in get_response
    method, args, hostargs, test = self.router(path, method, host)
NameError: name 'path' is not defined
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 238, in get_response
    return getattr(page_maker, method)(*args)
TypeError: Index() takes 1 positional argument but 2 were given
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 238, in get_response
    return getattr(page_maker, method)(*args)
TypeError: Index() takes 1 positional argument but 2 were given
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 238, in get_response
    return getattr(page_maker, method)(*args)
TypeError: Index() takes 1 positional argument but 2 were given
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 474, in __init__
    self._file_mtime = os.path.getmtime(self._file_name)
  File "/usr/lib/python3.6/genericpath.py", line 55, in getmtime
    return os.stat(filename).st_mtime
FileNotFoundError: [Errno 2] No such file or directory: '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 185, in AddTemplate
    self[name or location] = FileTemplate(template_path, parser=self)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 478, in __init__
    raise TemplateReadError('Cannot open: %r' % template_path)
uweb3.templateparser.TemplateReadError: Cannot open: '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 236, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/routes/login.py", line 35, in Login
    return self.parser.Parse('login.html')
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 204, in Parse
    return self[template].Parse(**replacements)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 163, in __getitem__
    self.AddTemplate(template)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 187, in AddTemplate
    raise TemplateReadError('Could not load template %r' % template_path)
uweb3.templateparser.TemplateReadError: Could not load template '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 474, in __init__
    self._file_mtime = os.path.getmtime(self._file_name)
  File "/usr/lib/python3.6/genericpath.py", line 55, in getmtime
    return os.stat(filename).st_mtime
FileNotFoundError: [Errno 2] No such file or directory: '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 185, in AddTemplate
    self[name or location] = FileTemplate(template_path, parser=self)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 478, in __init__
    raise TemplateReadError('Cannot open: %r' % template_path)
uweb3.templateparser.TemplateReadError: Cannot open: '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 236, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/routes/login.py", line 35, in Login
    return self.parser.Parse('login.html')
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 204, in Parse
    return self[template].Parse(**replacements)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 163, in __getitem__
    self.AddTemplate(template)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 187, in AddTemplate
    raise TemplateReadError('Could not load template %r' % template_path)
uweb3.templateparser.TemplateReadError: Could not load template '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 474, in __init__
    self._file_mtime = os.path.getmtime(self._file_name)
  File "/usr/lib/python3.6/genericpath.py", line 55, in getmtime
    return os.stat(filename).st_mtime
FileNotFoundError: [Errno 2] No such file or directory: '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 185, in AddTemplate
    self[name or location] = FileTemplate(template_path, parser=self)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 478, in __init__
    raise TemplateReadError('Cannot open: %r' % template_path)
uweb3.templateparser.TemplateReadError: Cannot open: '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 236, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/routes/login.py", line 35, in Login
    return self.parser.Parse('login.html')
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 204, in Parse
    return self[template].Parse(**replacements)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 163, in __getitem__
    self.AddTemplate(template)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 187, in AddTemplate
    raise TemplateReadError('Could not load template %r' % template_path)
uweb3.templateparser.TemplateReadError: Could not load template '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 474, in __init__
    self._file_mtime = os.path.getmtime(self._file_name)
  File "/usr/lib/python3.6/genericpath.py", line 55, in getmtime
    return os.stat(filename).st_mtime
FileNotFoundError: [Errno 2] No such file or directory: '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 185, in AddTemplate
    self[name or location] = FileTemplate(template_path, parser=self)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 478, in __init__
    raise TemplateReadError('Cannot open: %r' % template_path)
uweb3.templateparser.TemplateReadError: Cannot open: '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 236, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/routes/login.py", line 36, in Login
    return self.parser.Parse('login.html')
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 204, in Parse
    return self[template].Parse(**replacements)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 163, in __getitem__
    self.AddTemplate(template)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 187, in AddTemplate
    raise TemplateReadError('Could not load template %r' % template_path)
uweb3.templateparser.TemplateReadError: Could not load template '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 474, in __init__
    self._file_mtime = os.path.getmtime(self._file_name)
  File "/usr/lib/python3.6/genericpath.py", line 55, in getmtime
    return os.stat(filename).st_mtime
FileNotFoundError: [Errno 2] No such file or directory: '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 185, in AddTemplate
    self[name or location] = FileTemplate(template_path, parser=self)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 478, in __init__
    raise TemplateReadError('Cannot open: %r' % template_path)
uweb3.templateparser.TemplateReadError: Cannot open: '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 236, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/routes/login.py", line 36, in Login
    return self.parser.Parse('login.html')
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 204, in Parse
    return self[template].Parse(**replacements)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 163, in __getitem__
    self.AddTemplate(template)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 187, in AddTemplate
    raise TemplateReadError('Could not load template %r' % template_path)
uweb3.templateparser.TemplateReadError: Could not load template '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 474, in __init__
    self._file_mtime = os.path.getmtime(self._file_name)
  File "/usr/lib/python3.6/genericpath.py", line 55, in getmtime
    return os.stat(filename).st_mtime
FileNotFoundError: [Errno 2] No such file or directory: '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/404.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 185, in AddTemplate
    self[name or location] = FileTemplate(template_path, parser=self)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 478, in __init__
    raise TemplateReadError('Cannot open: %r' % template_path)
uweb3.templateparser.TemplateReadError: Cannot open: '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/404.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 236, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/base/pages.py", line 36, in FourOhFour
    return self.parser.Parse('404.html', path=path)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 204, in Parse
    return self[template].Parse(**replacements)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 163, in __getitem__
    self.AddTemplate(template)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 187, in AddTemplate
    raise TemplateReadError('Could not load template %r' % template_path)
uweb3.templateparser.TemplateReadError: Could not load template '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/404.html'
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 474, in __init__
    self._file_mtime = os.path.getmtime(self._file_name)
  File "/usr/lib/python3.6/genericpath.py", line 55, in getmtime
    return os.stat(filename).st_mtime
FileNotFoundError: [Errno 2] No such file or directory: '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/404.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 185, in AddTemplate
    self[name or location] = FileTemplate(template_path, parser=self)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 478, in __init__
    raise TemplateReadError('Cannot open: %r' % template_path)
uweb3.templateparser.TemplateReadError: Cannot open: '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/404.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 236, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/base/pages.py", line 36, in FourOhFour
    return self.parser.Parse('404.html', path=path)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 204, in Parse
    return self[template].Parse(**replacements)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 163, in __getitem__
    self.AddTemplate(template)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 187, in AddTemplate
    raise TemplateReadError('Could not load template %r' % template_path)
uweb3.templateparser.TemplateReadError: Could not load template '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/404.html'
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 474, in __init__
    self._file_mtime = os.path.getmtime(self._file_name)
  File "/usr/lib/python3.6/genericpath.py", line 55, in getmtime
    return os.stat(filename).st_mtime
FileNotFoundError: [Errno 2] No such file or directory: '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 185, in AddTemplate
    self[name or location] = FileTemplate(template_path, parser=self)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 478, in __init__
    raise TemplateReadError('Cannot open: %r' % template_path)
uweb3.templateparser.TemplateReadError: Cannot open: '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 236, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/routes/login.py", line 36, in Login
    return self.parser.Parse('login.html')
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 204, in Parse
    return self[template].Parse(**replacements)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 163, in __getitem__
    self.AddTemplate(template)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 187, in AddTemplate
    raise TemplateReadError('Could not load template %r' % template_path)
uweb3.templateparser.TemplateReadError: Could not load template '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 474, in __init__
    self._file_mtime = os.path.getmtime(self._file_name)
  File "/usr/lib/python3.6/genericpath.py", line 55, in getmtime
    return os.stat(filename).st_mtime
FileNotFoundError: [Errno 2] No such file or directory: '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 185, in AddTemplate
    self[name or location] = FileTemplate(template_path, parser=self)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 478, in __init__
    raise TemplateReadError('Cannot open: %r' % template_path)
uweb3.templateparser.TemplateReadError: Cannot open: '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 236, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/routes/login.py", line 36, in Login
    return self.parser.Parse('login.html')
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 204, in Parse
    return self[template].Parse(**replacements)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 163, in __getitem__
    self.AddTemplate(template)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 187, in AddTemplate
    raise TemplateReadError('Could not load template %r' % template_path)
uweb3.templateparser.TemplateReadError: Could not load template '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 474, in __init__
    self._file_mtime = os.path.getmtime(self._file_name)
  File "/usr/lib/python3.6/genericpath.py", line 55, in getmtime
    return os.stat(filename).st_mtime
FileNotFoundError: [Errno 2] No such file or directory: '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 185, in AddTemplate
    self[name or location] = FileTemplate(template_path, parser=self)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 478, in __init__
    raise TemplateReadError('Cannot open: %r' % template_path)
uweb3.templateparser.TemplateReadError: Cannot open: '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 236, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/routes/login.py", line 36, in Login
    return self.parser.Parse('login.html')
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 204, in Parse
    return self[template].Parse(**replacements)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 163, in __getitem__
    self.AddTemplate(template)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 187, in AddTemplate
    raise TemplateReadError('Could not load template %r' % template_path)
uweb3.templateparser.TemplateReadError: Could not load template '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 474, in __init__
    self._file_mtime = os.path.getmtime(self._file_name)
  File "/usr/lib/python3.6/genericpath.py", line 55, in getmtime
    return os.stat(filename).st_mtime
FileNotFoundError: [Errno 2] No such file or directory: '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 185, in AddTemplate
    self[name or location] = FileTemplate(template_path, parser=self)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 478, in __init__
    raise TemplateReadError('Cannot open: %r' % template_path)
uweb3.templateparser.TemplateReadError: Cannot open: '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 236, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/routes/login.py", line 36, in Login
    return self.parser.Parse('login.html')
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 204, in Parse
    return self[template].Parse(**replacements)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 163, in __getitem__
    self.AddTemplate(template)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 187, in AddTemplate
    raise TemplateReadError('Could not load template %r' % template_path)
uweb3.templateparser.TemplateReadError: Could not load template '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 474, in __init__
    self._file_mtime = os.path.getmtime(self._file_name)
  File "/usr/lib/python3.6/genericpath.py", line 55, in getmtime
    return os.stat(filename).st_mtime
FileNotFoundError: [Errno 2] No such file or directory: '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 185, in AddTemplate
    self[name or location] = FileTemplate(template_path, parser=self)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 478, in __init__
    raise TemplateReadError('Cannot open: %r' % template_path)
uweb3.templateparser.TemplateReadError: Cannot open: '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 236, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/routes/login.py", line 36, in Login
    return self.parser.Parse('login.html')
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 204, in Parse
    return self[template].Parse(**replacements)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 163, in __getitem__
    self.AddTemplate(template)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 187, in AddTemplate
    raise TemplateReadError('Could not load template %r' % template_path)
uweb3.templateparser.TemplateReadError: Could not load template '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 474, in __init__
    self._file_mtime = os.path.getmtime(self._file_name)
  File "/usr/lib/python3.6/genericpath.py", line 55, in getmtime
    return os.stat(filename).st_mtime
FileNotFoundError: [Errno 2] No such file or directory: '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 185, in AddTemplate
    self[name or location] = FileTemplate(template_path, parser=self)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 478, in __init__
    raise TemplateReadError('Cannot open: %r' % template_path)
uweb3.templateparser.TemplateReadError: Cannot open: '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 236, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/routes/login.py", line 36, in Login
    return self.parser.Parse('login.html')
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 204, in Parse
    return self[template].Parse(**replacements)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 163, in __getitem__
    self.AddTemplate(template)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 187, in AddTemplate
    raise TemplateReadError('Could not load template %r' % template_path)
uweb3.templateparser.TemplateReadError: Could not load template '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 474, in __init__
    self._file_mtime = os.path.getmtime(self._file_name)
  File "/usr/lib/python3.6/genericpath.py", line 55, in getmtime
    return os.stat(filename).st_mtime
FileNotFoundError: [Errno 2] No such file or directory: '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 185, in AddTemplate
    self[name or location] = FileTemplate(template_path, parser=self)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 478, in __init__
    raise TemplateReadError('Cannot open: %r' % template_path)
uweb3.templateparser.TemplateReadError: Cannot open: '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 236, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/routes/login.py", line 36, in Login
    return self.parser.Parse('login.html')
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 204, in Parse
    return self[template].Parse(**replacements)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 163, in __getitem__
    self.AddTemplate(template)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 187, in AddTemplate
    raise TemplateReadError('Could not load template %r' % template_path)
uweb3.templateparser.TemplateReadError: Could not load template '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 474, in __init__
    self._file_mtime = os.path.getmtime(self._file_name)
  File "/usr/lib/python3.6/genericpath.py", line 55, in getmtime
    return os.stat(filename).st_mtime
FileNotFoundError: [Errno 2] No such file or directory: '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 185, in AddTemplate
    self[name or location] = FileTemplate(template_path, parser=self)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 478, in __init__
    raise TemplateReadError('Cannot open: %r' % template_path)
uweb3.templateparser.TemplateReadError: Cannot open: '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 236, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/routes/login.py", line 36, in Login
    return self.parser.Parse('login.html')
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 204, in Parse
    return self[template].Parse(**replacements)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 163, in __getitem__
    self.AddTemplate(template)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 187, in AddTemplate
    raise TemplateReadError('Could not load template %r' % template_path)
uweb3.templateparser.TemplateReadError: Could not load template '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 474, in __init__
    self._file_mtime = os.path.getmtime(self._file_name)
  File "/usr/lib/python3.6/genericpath.py", line 55, in getmtime
    return os.stat(filename).st_mtime
FileNotFoundError: [Errno 2] No such file or directory: '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 185, in AddTemplate
    self[name or location] = FileTemplate(template_path, parser=self)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 478, in __init__
    raise TemplateReadError('Cannot open: %r' % template_path)
uweb3.templateparser.TemplateReadError: Cannot open: '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 236, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/routes/login.py", line 36, in Login
    return self.parser.Parse('login.html')
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 204, in Parse
    return self[template].Parse(**replacements)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 163, in __getitem__
    self.AddTemplate(template)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 187, in AddTemplate
    raise TemplateReadError('Could not load template %r' % template_path)
uweb3.templateparser.TemplateReadError: Could not load template '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 474, in __init__
    self._file_mtime = os.path.getmtime(self._file_name)
  File "/usr/lib/python3.6/genericpath.py", line 55, in getmtime
    return os.stat(filename).st_mtime
FileNotFoundError: [Errno 2] No such file or directory: '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 185, in AddTemplate
    self[name or location] = FileTemplate(template_path, parser=self)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 478, in __init__
    raise TemplateReadError('Cannot open: %r' % template_path)
uweb3.templateparser.TemplateReadError: Cannot open: '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 236, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/routes/login.py", line 36, in Login
    return self.parser.Parse('login.html')
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 204, in Parse
    return self[template].Parse(**replacements)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 163, in __getitem__
    self.AddTemplate(template)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 187, in AddTemplate
    raise TemplateReadError('Could not load template %r' % template_path)
uweb3.templateparser.TemplateReadError: Could not load template '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 474, in __init__
    self._file_mtime = os.path.getmtime(self._file_name)
  File "/usr/lib/python3.6/genericpath.py", line 55, in getmtime
    return os.stat(filename).st_mtime
FileNotFoundError: [Errno 2] No such file or directory: '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 185, in AddTemplate
    self[name or location] = FileTemplate(template_path, parser=self)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 478, in __init__
    raise TemplateReadError('Cannot open: %r' % template_path)
uweb3.templateparser.TemplateReadError: Cannot open: '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 236, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/routes/login.py", line 36, in Login
    return self.parser.Parse('login.html')
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 204, in Parse
    return self[template].Parse(**replacements)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 163, in __getitem__
    self.AddTemplate(template)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 187, in AddTemplate
    raise TemplateReadError('Could not load template %r' % template_path)
uweb3.templateparser.TemplateReadError: Could not load template '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 474, in __init__
    self._file_mtime = os.path.getmtime(self._file_name)
  File "/usr/lib/python3.6/genericpath.py", line 55, in getmtime
    return os.stat(filename).st_mtime
FileNotFoundError: [Errno 2] No such file or directory: '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 185, in AddTemplate
    self[name or location] = FileTemplate(template_path, parser=self)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 478, in __init__
    raise TemplateReadError('Cannot open: %r' % template_path)
uweb3.templateparser.TemplateReadError: Cannot open: '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 236, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/routes/login.py", line 36, in Login
    return self.parser.Parse('login.html')
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 204, in Parse
    return self[template].Parse(**replacements)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 163, in __getitem__
    self.AddTemplate(template)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 187, in AddTemplate
    raise TemplateReadError('Could not load template %r' % template_path)
uweb3.templateparser.TemplateReadError: Could not load template '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 474, in __init__
    self._file_mtime = os.path.getmtime(self._file_name)
  File "/usr/lib/python3.6/genericpath.py", line 55, in getmtime
    return os.stat(filename).st_mtime
FileNotFoundError: [Errno 2] No such file or directory: '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 185, in AddTemplate
    self[name or location] = FileTemplate(template_path, parser=self)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 478, in __init__
    raise TemplateReadError('Cannot open: %r' % template_path)
uweb3.templateparser.TemplateReadError: Cannot open: '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 236, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/routes/login.py", line 36, in Login
    return self.parser.Parse('login.html')
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 204, in Parse
    return self[template].Parse(**replacements)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 163, in __getitem__
    self.AddTemplate(template)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 187, in AddTemplate
    raise TemplateReadError('Could not load template %r' % template_path)
uweb3.templateparser.TemplateReadError: Could not load template '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 474, in __init__
    self._file_mtime = os.path.getmtime(self._file_name)
  File "/usr/lib/python3.6/genericpath.py", line 55, in getmtime
    return os.stat(filename).st_mtime
FileNotFoundError: [Errno 2] No such file or directory: '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 185, in AddTemplate
    self[name or location] = FileTemplate(template_path, parser=self)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 478, in __init__
    raise TemplateReadError('Cannot open: %r' % template_path)
uweb3.templateparser.TemplateReadError: Cannot open: '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 236, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/routes/login.py", line 36, in Login
    return self.parser.Parse('login.html')
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 204, in Parse
    return self[template].Parse(**replacements)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 163, in __getitem__
    self.AddTemplate(template)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 187, in AddTemplate
    raise TemplateReadError('Could not load template %r' % template_path)
uweb3.templateparser.TemplateReadError: Could not load template '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 474, in __init__
    self._file_mtime = os.path.getmtime(self._file_name)
  File "/usr/lib/python3.6/genericpath.py", line 55, in getmtime
    return os.stat(filename).st_mtime
FileNotFoundError: [Errno 2] No such file or directory: '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 185, in AddTemplate
    self[name or location] = FileTemplate(template_path, parser=self)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 478, in __init__
    raise TemplateReadError('Cannot open: %r' % template_path)
uweb3.templateparser.TemplateReadError: Cannot open: '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 236, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/routes/login.py", line 36, in Login
    return self.parser.Parse('login.html')
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 204, in Parse
    return self[template].Parse(**replacements)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 163, in __getitem__
    self.AddTemplate(template)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 187, in AddTemplate
    raise TemplateReadError('Could not load template %r' % template_path)
uweb3.templateparser.TemplateReadError: Could not load template '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 474, in __init__
    self._file_mtime = os.path.getmtime(self._file_name)
  File "/usr/lib/python3.6/genericpath.py", line 55, in getmtime
    return os.stat(filename).st_mtime
FileNotFoundError: [Errno 2] No such file or directory: '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 185, in AddTemplate
    self[name or location] = FileTemplate(template_path, parser=self)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 478, in __init__
    raise TemplateReadError('Cannot open: %r' % template_path)
uweb3.templateparser.TemplateReadError: Cannot open: '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 236, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/routes/login.py", line 36, in Login
    return self.parser.Parse('login.html')
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 204, in Parse
    return self[template].Parse(**replacements)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 163, in __getitem__
    self.AddTemplate(template)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 187, in AddTemplate
    raise TemplateReadError('Could not load template %r' % template_path)
uweb3.templateparser.TemplateReadError: Could not load template '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 474, in __init__
    self._file_mtime = os.path.getmtime(self._file_name)
  File "/usr/lib/python3.6/genericpath.py", line 55, in getmtime
    return os.stat(filename).st_mtime
FileNotFoundError: [Errno 2] No such file or directory: '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 185, in AddTemplate
    self[name or location] = FileTemplate(template_path, parser=self)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 478, in __init__
    raise TemplateReadError('Cannot open: %r' % template_path)
uweb3.templateparser.TemplateReadError: Cannot open: '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 236, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/routes/login.py", line 36, in Login
    return self.parser.Parse('login.html')
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 204, in Parse
    return self[template].Parse(**replacements)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 163, in __getitem__
    self.AddTemplate(template)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 187, in AddTemplate
    raise TemplateReadError('Could not load template %r' % template_path)
uweb3.templateparser.TemplateReadError: Could not load template '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 474, in __init__
    self._file_mtime = os.path.getmtime(self._file_name)
  File "/usr/lib/python3.6/genericpath.py", line 55, in getmtime
    return os.stat(filename).st_mtime
FileNotFoundError: [Errno 2] No such file or directory: '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 185, in AddTemplate
    self[name or location] = FileTemplate(template_path, parser=self)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 478, in __init__
    raise TemplateReadError('Cannot open: %r' % template_path)
uweb3.templateparser.TemplateReadError: Cannot open: '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 236, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/routes/login.py", line 36, in Login
    return self.parser.Parse('login.html')
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 204, in Parse
    return self[template].Parse(**replacements)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 163, in __getitem__
    self.AddTemplate(template)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 187, in AddTemplate
    raise TemplateReadError('Could not load template %r' % template_path)
uweb3.templateparser.TemplateReadError: Could not load template '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 474, in __init__
    self._file_mtime = os.path.getmtime(self._file_name)
  File "/usr/lib/python3.6/genericpath.py", line 55, in getmtime
    return os.stat(filename).st_mtime
FileNotFoundError: [Errno 2] No such file or directory: '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/index.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 185, in AddTemplate
    self[name or location] = FileTemplate(template_path, parser=self)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 478, in __init__
    raise TemplateReadError('Cannot open: %r' % template_path)
uweb3.templateparser.TemplateReadError: Cannot open: '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/index.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 236, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/base/pages.py", line 27, in Index
    return self.parser.Parse('index.html')
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 204, in Parse
    return self[template].Parse(**replacements)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 163, in __getitem__
    self.AddTemplate(template)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 187, in AddTemplate
    raise TemplateReadError('Could not load template %r' % template_path)
uweb3.templateparser.TemplateReadError: Could not load template '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/index.html'
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 474, in __init__
    self._file_mtime = os.path.getmtime(self._file_name)
  File "/usr/lib/python3.6/genericpath.py", line 55, in getmtime
    return os.stat(filename).st_mtime
FileNotFoundError: [Errno 2] No such file or directory: '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/index.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 185, in AddTemplate
    self[name or location] = FileTemplate(template_path, parser=self)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 478, in __init__
    raise TemplateReadError('Cannot open: %r' % template_path)
uweb3.templateparser.TemplateReadError: Cannot open: '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/index.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 236, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/base/pages.py", line 27, in Index
    return self.parser.Parse('index.html')
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 204, in Parse
    return self[template].Parse(**replacements)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 163, in __getitem__
    self.AddTemplate(template)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 187, in AddTemplate
    raise TemplateReadError('Could not load template %r' % template_path)
uweb3.templateparser.TemplateReadError: Could not load template '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/index.html'
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 474, in __init__
    self._file_mtime = os.path.getmtime(self._file_name)
  File "/usr/lib/python3.6/genericpath.py", line 55, in getmtime
    return os.stat(filename).st_mtime
FileNotFoundError: [Errno 2] No such file or directory: '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/index.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 185, in AddTemplate
    self[name or location] = FileTemplate(template_path, parser=self)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 478, in __init__
    raise TemplateReadError('Cannot open: %r' % template_path)
uweb3.templateparser.TemplateReadError: Cannot open: '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/index.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 236, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/base/pages.py", line 27, in Index
    return self.parser.Parse('index.html')
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 204, in Parse
    return self[template].Parse(**replacements)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 163, in __getitem__
    self.AddTemplate(template)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 187, in AddTemplate
    raise TemplateReadError('Could not load template %r' % template_path)
uweb3.templateparser.TemplateReadError: Could not load template '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/index.html'
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 474, in __init__
    self._file_mtime = os.path.getmtime(self._file_name)
  File "/usr/lib/python3.6/genericpath.py", line 55, in getmtime
    return os.stat(filename).st_mtime
FileNotFoundError: [Errno 2] No such file or directory: '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/index.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 185, in AddTemplate
    self[name or location] = FileTemplate(template_path, parser=self)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 478, in __init__
    raise TemplateReadError('Cannot open: %r' % template_path)
uweb3.templateparser.TemplateReadError: Cannot open: '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/index.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 236, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/base/pages.py", line 27, in Index
    return self.parser.Parse('index.html')
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 204, in Parse
    return self[template].Parse(**replacements)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 163, in __getitem__
    self.AddTemplate(template)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 187, in AddTemplate
    raise TemplateReadError('Could not load template %r' % template_path)
uweb3.templateparser.TemplateReadError: Could not load template '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/index.html'
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 474, in __init__
    self._file_mtime = os.path.getmtime(self._file_name)
  File "/usr/lib/python3.6/genericpath.py", line 55, in getmtime
    return os.stat(filename).st_mtime
FileNotFoundError: [Errno 2] No such file or directory: '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/index.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 185, in AddTemplate
    self[name or location] = FileTemplate(template_path, parser=self)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 478, in __init__
    raise TemplateReadError('Cannot open: %r' % template_path)
uweb3.templateparser.TemplateReadError: Cannot open: '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/index.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 236, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/base/pages.py", line 27, in Index
    return self.parser.Parse('index.html')
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 204, in Parse
    return self[template].Parse(**replacements)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 163, in __getitem__
    self.AddTemplate(template)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 187, in AddTemplate
    raise TemplateReadError('Could not load template %r' % template_path)
uweb3.templateparser.TemplateReadError: Could not load template '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/index.html'
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 474, in __init__
    self._file_mtime = os.path.getmtime(self._file_name)
  File "/usr/lib/python3.6/genericpath.py", line 55, in getmtime
    return os.stat(filename).st_mtime
FileNotFoundError: [Errno 2] No such file or directory: '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/index.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 185, in AddTemplate
    self[name or location] = FileTemplate(template_path, parser=self)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 478, in __init__
    raise TemplateReadError('Cannot open: %r' % template_path)
uweb3.templateparser.TemplateReadError: Cannot open: '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/index.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 236, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/base/pages.py", line 27, in Index
    return self.parser.Parse('index.html')
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 204, in Parse
    return self[template].Parse(**replacements)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 163, in __getitem__
    self.AddTemplate(template)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 187, in AddTemplate
    raise TemplateReadError('Could not load template %r' % template_path)
uweb3.templateparser.TemplateReadError: Could not load template '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/index.html'
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 474, in __init__
    self._file_mtime = os.path.getmtime(self._file_name)
  File "/usr/lib/python3.6/genericpath.py", line 55, in getmtime
    return os.stat(filename).st_mtime
FileNotFoundError: [Errno 2] No such file or directory: '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/index.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 185, in AddTemplate
    self[name or location] = FileTemplate(template_path, parser=self)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 478, in __init__
    raise TemplateReadError('Cannot open: %r' % template_path)
uweb3.templateparser.TemplateReadError: Cannot open: '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/index.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 236, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/base/pages.py", line 27, in Index
    return self.parser.Parse('index.html')
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 204, in Parse
    return self[template].Parse(**replacements)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 163, in __getitem__
    self.AddTemplate(template)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 187, in AddTemplate
    raise TemplateReadError('Could not load template %r' % template_path)
uweb3.templateparser.TemplateReadError: Could not load template '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/index.html'
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 474, in __init__
    self._file_mtime = os.path.getmtime(self._file_name)
  File "/usr/lib/python3.6/genericpath.py", line 55, in getmtime
    return os.stat(filename).st_mtime
FileNotFoundError: [Errno 2] No such file or directory: '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 185, in AddTemplate
    self[name or location] = FileTemplate(template_path, parser=self)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 478, in __init__
    raise TemplateReadError('Cannot open: %r' % template_path)
uweb3.templateparser.TemplateReadError: Cannot open: '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 236, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/routes/login.py", line 35, in Login
    return self.parser.Parse('login.html')
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 204, in Parse
    return self[template].Parse(**replacements)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 163, in __getitem__
    self.AddTemplate(template)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 187, in AddTemplate
    raise TemplateReadError('Could not load template %r' % template_path)
uweb3.templateparser.TemplateReadError: Could not load template '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 474, in __init__
    self._file_mtime = os.path.getmtime(self._file_name)
  File "/usr/lib/python3.6/genericpath.py", line 55, in getmtime
    return os.stat(filename).st_mtime
FileNotFoundError: [Errno 2] No such file or directory: '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 185, in AddTemplate
    self[name or location] = FileTemplate(template_path, parser=self)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 478, in __init__
    raise TemplateReadError('Cannot open: %r' % template_path)
uweb3.templateparser.TemplateReadError: Cannot open: '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 236, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/routes/login.py", line 31, in Login
    return self.parser.Parse('login.html')
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 204, in Parse
    return self[template].Parse(**replacements)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 163, in __getitem__
    self.AddTemplate(template)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 187, in AddTemplate
    raise TemplateReadError('Could not load template %r' % template_path)
uweb3.templateparser.TemplateReadError: Could not load template '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 474, in __init__
    self._file_mtime = os.path.getmtime(self._file_name)
  File "/usr/lib/python3.6/genericpath.py", line 55, in getmtime
    return os.stat(filename).st_mtime
FileNotFoundError: [Errno 2] No such file or directory: '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 185, in AddTemplate
    self[name or location] = FileTemplate(template_path, parser=self)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 478, in __init__
    raise TemplateReadError('Cannot open: %r' % template_path)
uweb3.templateparser.TemplateReadError: Cannot open: '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 236, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/routes/login.py", line 31, in Login
    return self.parser.Parse('login.html')
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 204, in Parse
    return self[template].Parse(**replacements)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 163, in __getitem__
    self.AddTemplate(template)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 187, in AddTemplate
    raise TemplateReadError('Could not load template %r' % template_path)
uweb3.templateparser.TemplateReadError: Could not load template '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 474, in __init__
    self._file_mtime = os.path.getmtime(self._file_name)
  File "/usr/lib/python3.6/genericpath.py", line 55, in getmtime
    return os.stat(filename).st_mtime
FileNotFoundError: [Errno 2] No such file or directory: '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 185, in AddTemplate
    self[name or location] = FileTemplate(template_path, parser=self)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 478, in __init__
    raise TemplateReadError('Cannot open: %r' % template_path)
uweb3.templateparser.TemplateReadError: Cannot open: '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 236, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/routes/login.py", line 31, in Login
    return self.parser.Parse('login.html')
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 204, in Parse
    return self[template].Parse(**replacements)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 163, in __getitem__
    self.AddTemplate(template)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 187, in AddTemplate
    raise TemplateReadError('Could not load template %r' % template_path)
uweb3.templateparser.TemplateReadError: Could not load template '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 474, in __init__
    self._file_mtime = os.path.getmtime(self._file_name)
  File "/usr/lib/python3.6/genericpath.py", line 55, in getmtime
    return os.stat(filename).st_mtime
FileNotFoundError: [Errno 2] No such file or directory: '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 185, in AddTemplate
    self[name or location] = FileTemplate(template_path, parser=self)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 478, in __init__
    raise TemplateReadError('Cannot open: %r' % template_path)
uweb3.templateparser.TemplateReadError: Cannot open: '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 236, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/routes/login.py", line 31, in Login
    return self.parser.Parse('login.html')
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 204, in Parse
    return self[template].Parse(**replacements)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 163, in __getitem__
    self.AddTemplate(template)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 187, in AddTemplate
    raise TemplateReadError('Could not load template %r' % template_path)
uweb3.templateparser.TemplateReadError: Could not load template '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 474, in __init__
    self._file_mtime = os.path.getmtime(self._file_name)
  File "/usr/lib/python3.6/genericpath.py", line 55, in getmtime
    return os.stat(filename).st_mtime
FileNotFoundError: [Errno 2] No such file or directory: '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 185, in AddTemplate
    self[name or location] = FileTemplate(template_path, parser=self)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 478, in __init__
    raise TemplateReadError('Cannot open: %r' % template_path)
uweb3.templateparser.TemplateReadError: Cannot open: '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 236, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/routes/login.py", line 31, in Login
    return self.parser.Parse('login.html')
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 204, in Parse
    return self[template].Parse(**replacements)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 163, in __getitem__
    self.AddTemplate(template)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 187, in AddTemplate
    raise TemplateReadError('Could not load template %r' % template_path)
uweb3.templateparser.TemplateReadError: Could not load template '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 474, in __init__
    self._file_mtime = os.path.getmtime(self._file_name)
  File "/usr/lib/python3.6/genericpath.py", line 55, in getmtime
    return os.stat(filename).st_mtime
FileNotFoundError: [Errno 2] No such file or directory: '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 185, in AddTemplate
    self[name or location] = FileTemplate(template_path, parser=self)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 478, in __init__
    raise TemplateReadError('Cannot open: %r' % template_path)
uweb3.templateparser.TemplateReadError: Cannot open: '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 236, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/routes/login.py", line 31, in Login
    return self.parser.Parse('login.html')
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 204, in Parse
    return self[template].Parse(**replacements)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 163, in __getitem__
    self.AddTemplate(template)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 187, in AddTemplate
    raise TemplateReadError('Could not load template %r' % template_path)
uweb3.templateparser.TemplateReadError: Could not load template '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 474, in __init__
    self._file_mtime = os.path.getmtime(self._file_name)
  File "/usr/lib/python3.6/genericpath.py", line 55, in getmtime
    return os.stat(filename).st_mtime
FileNotFoundError: [Errno 2] No such file or directory: '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 185, in AddTemplate
    self[name or location] = FileTemplate(template_path, parser=self)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 478, in __init__
    raise TemplateReadError('Cannot open: %r' % template_path)
uweb3.templateparser.TemplateReadError: Cannot open: '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 236, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/routes/login.py", line 31, in Login
    return self.parser.Parse('login.html')
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 204, in Parse
    return self[template].Parse(**replacements)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 163, in __getitem__
    self.AddTemplate(template)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 187, in AddTemplate
    raise TemplateReadError('Could not load template %r' % template_path)
uweb3.templateparser.TemplateReadError: Could not load template '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 474, in __init__
    self._file_mtime = os.path.getmtime(self._file_name)
  File "/usr/lib/python3.6/genericpath.py", line 55, in getmtime
    return os.stat(filename).st_mtime
FileNotFoundError: [Errno 2] No such file or directory: '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 185, in AddTemplate
    self[name or location] = FileTemplate(template_path, parser=self)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 478, in __init__
    raise TemplateReadError('Cannot open: %r' % template_path)
uweb3.templateparser.TemplateReadError: Cannot open: '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 236, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/routes/login.py", line 31, in Login
    return self.parser.Parse('login.html')
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 204, in Parse
    return self[template].Parse(**replacements)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 163, in __getitem__
    self.AddTemplate(template)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 187, in AddTemplate
    raise TemplateReadError('Could not load template %r' % template_path)
uweb3.templateparser.TemplateReadError: Could not load template '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 474, in __init__
    self._file_mtime = os.path.getmtime(self._file_name)
  File "/usr/lib/python3.6/genericpath.py", line 55, in getmtime
    return os.stat(filename).st_mtime
FileNotFoundError: [Errno 2] No such file or directory: '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 185, in AddTemplate
    self[name or location] = FileTemplate(template_path, parser=self)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 478, in __init__
    raise TemplateReadError('Cannot open: %r' % template_path)
uweb3.templateparser.TemplateReadError: Cannot open: '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 236, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/routes/login.py", line 31, in Login
    return self.parser.Parse('login.html')
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 204, in Parse
    return self[template].Parse(**replacements)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 163, in __getitem__
    self.AddTemplate(template)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 187, in AddTemplate
    raise TemplateReadError('Could not load template %r' % template_path)
uweb3.templateparser.TemplateReadError: Could not load template '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 474, in __init__
    self._file_mtime = os.path.getmtime(self._file_name)
  File "/usr/lib/python3.6/genericpath.py", line 55, in getmtime
    return os.stat(filename).st_mtime
FileNotFoundError: [Errno 2] No such file or directory: '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 185, in AddTemplate
    self[name or location] = FileTemplate(template_path, parser=self)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 478, in __init__
    raise TemplateReadError('Cannot open: %r' % template_path)
uweb3.templateparser.TemplateReadError: Cannot open: '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 236, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/routes/login.py", line 31, in Login
    return self.parser.Parse('login.html')
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 204, in Parse
    return self[template].Parse(**replacements)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 163, in __getitem__
    self.AddTemplate(template)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 187, in AddTemplate
    raise TemplateReadError('Could not load template %r' % template_path)
uweb3.templateparser.TemplateReadError: Could not load template '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 474, in __init__
    self._file_mtime = os.path.getmtime(self._file_name)
  File "/usr/lib/python3.6/genericpath.py", line 55, in getmtime
    return os.stat(filename).st_mtime
FileNotFoundError: [Errno 2] No such file or directory: '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 185, in AddTemplate
    self[name or location] = FileTemplate(template_path, parser=self)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 478, in __init__
    raise TemplateReadError('Cannot open: %r' % template_path)
uweb3.templateparser.TemplateReadError: Cannot open: '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 236, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/routes/login.py", line 31, in Login
    return self.parser.Parse('login.html')
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 204, in Parse
    return self[template].Parse(**replacements)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 163, in __getitem__
    self.AddTemplate(template)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 187, in AddTemplate
    raise TemplateReadError('Could not load template %r' % template_path)
uweb3.templateparser.TemplateReadError: Could not load template '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 474, in __init__
    self._file_mtime = os.path.getmtime(self._file_name)
  File "/usr/lib/python3.6/genericpath.py", line 55, in getmtime
    return os.stat(filename).st_mtime
FileNotFoundError: [Errno 2] No such file or directory: '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 185, in AddTemplate
    self[name or location] = FileTemplate(template_path, parser=self)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 478, in __init__
    raise TemplateReadError('Cannot open: %r' % template_path)
uweb3.templateparser.TemplateReadError: Cannot open: '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 236, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/routes/login.py", line 31, in Login
    return self.parser.Parse('login.html')
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 204, in Parse
    return self[template].Parse(**replacements)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 163, in __getitem__
    self.AddTemplate(template)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 187, in AddTemplate
    raise TemplateReadError('Could not load template %r' % template_path)
uweb3.templateparser.TemplateReadError: Could not load template '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 474, in __init__
    self._file_mtime = os.path.getmtime(self._file_name)
  File "/usr/lib/python3.6/genericpath.py", line 55, in getmtime
    return os.stat(filename).st_mtime
FileNotFoundError: [Errno 2] No such file or directory: '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 185, in AddTemplate
    self[name or location] = FileTemplate(template_path, parser=self)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 478, in __init__
    raise TemplateReadError('Cannot open: %r' % template_path)
uweb3.templateparser.TemplateReadError: Cannot open: '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 236, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/routes/login.py", line 31, in Login
    return self.parser.Parse('login.html')
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 204, in Parse
    return self[template].Parse(**replacements)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 163, in __getitem__
    self.AddTemplate(template)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 187, in AddTemplate
    raise TemplateReadError('Could not load template %r' % template_path)
uweb3.templateparser.TemplateReadError: Could not load template '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 474, in __init__
    self._file_mtime = os.path.getmtime(self._file_name)
  File "/usr/lib/python3.6/genericpath.py", line 55, in getmtime
    return os.stat(filename).st_mtime
FileNotFoundError: [Errno 2] No such file or directory: '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 185, in AddTemplate
    self[name or location] = FileTemplate(template_path, parser=self)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 478, in __init__
    raise TemplateReadError('Cannot open: %r' % template_path)
uweb3.templateparser.TemplateReadError: Cannot open: '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 236, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/routes/login.py", line 31, in Login
    return self.parser.Parse('login.html')
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 204, in Parse
    return self[template].Parse(**replacements)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 163, in __getitem__
    self.AddTemplate(template)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 187, in AddTemplate
    raise TemplateReadError('Could not load template %r' % template_path)
uweb3.templateparser.TemplateReadError: Could not load template '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 474, in __init__
    self._file_mtime = os.path.getmtime(self._file_name)
  File "/usr/lib/python3.6/genericpath.py", line 55, in getmtime
    return os.stat(filename).st_mtime
FileNotFoundError: [Errno 2] No such file or directory: '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 185, in AddTemplate
    self[name or location] = FileTemplate(template_path, parser=self)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 478, in __init__
    raise TemplateReadError('Cannot open: %r' % template_path)
uweb3.templateparser.TemplateReadError: Cannot open: '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 236, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/routes/login.py", line 31, in Login
    return self.parser.Parse('login.html')
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 204, in Parse
    return self[template].Parse(**replacements)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 163, in __getitem__
    self.AddTemplate(template)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 187, in AddTemplate
    raise TemplateReadError('Could not load template %r' % template_path)
uweb3.templateparser.TemplateReadError: Could not load template '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 474, in __init__
    self._file_mtime = os.path.getmtime(self._file_name)
  File "/usr/lib/python3.6/genericpath.py", line 55, in getmtime
    return os.stat(filename).st_mtime
FileNotFoundError: [Errno 2] No such file or directory: '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 185, in AddTemplate
    self[name or location] = FileTemplate(template_path, parser=self)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 478, in __init__
    raise TemplateReadError('Cannot open: %r' % template_path)
uweb3.templateparser.TemplateReadError: Cannot open: '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 236, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/routes/login.py", line 31, in Login
    return self.parser.Parse('login.html')
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 204, in Parse
    return self[template].Parse(**replacements)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 163, in __getitem__
    self.AddTemplate(template)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 187, in AddTemplate
    raise TemplateReadError('Could not load template %r' % template_path)
uweb3.templateparser.TemplateReadError: Could not load template '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 474, in __init__
    self._file_mtime = os.path.getmtime(self._file_name)
  File "/usr/lib/python3.6/genericpath.py", line 55, in getmtime
    return os.stat(filename).st_mtime
FileNotFoundError: [Errno 2] No such file or directory: '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 185, in AddTemplate
    self[name or location] = FileTemplate(template_path, parser=self)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 478, in __init__
    raise TemplateReadError('Cannot open: %r' % template_path)
uweb3.templateparser.TemplateReadError: Cannot open: '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 236, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/routes/login.py", line 31, in Login
    return self.parser.Parse('login.html')
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 204, in Parse
    return self[template].Parse(**replacements)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 163, in __getitem__
    self.AddTemplate(template)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 187, in AddTemplate
    raise TemplateReadError('Could not load template %r' % template_path)
uweb3.templateparser.TemplateReadError: Could not load template '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 474, in __init__
    self._file_mtime = os.path.getmtime(self._file_name)
  File "/usr/lib/python3.6/genericpath.py", line 55, in getmtime
    return os.stat(filename).st_mtime
FileNotFoundError: [Errno 2] No such file or directory: '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 185, in AddTemplate
    self[name or location] = FileTemplate(template_path, parser=self)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 478, in __init__
    raise TemplateReadError('Cannot open: %r' % template_path)
uweb3.templateparser.TemplateReadError: Cannot open: '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 236, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/routes/login.py", line 31, in Login
    return self.parser.Parse('login.html')
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 204, in Parse
    return self[template].Parse(**replacements)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 163, in __getitem__
    self.AddTemplate(template)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 187, in AddTemplate
    raise TemplateReadError('Could not load template %r' % template_path)
uweb3.templateparser.TemplateReadError: Could not load template '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 474, in __init__
    self._file_mtime = os.path.getmtime(self._file_name)
  File "/usr/lib/python3.6/genericpath.py", line 55, in getmtime
    return os.stat(filename).st_mtime
FileNotFoundError: [Errno 2] No such file or directory: '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 185, in AddTemplate
    self[name or location] = FileTemplate(template_path, parser=self)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 478, in __init__
    raise TemplateReadError('Cannot open: %r' % template_path)
uweb3.templateparser.TemplateReadError: Cannot open: '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 236, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/routes/login.py", line 31, in Login
    return self.parser.Parse('login.html')
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 204, in Parse
    return self[template].Parse(**replacements)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 163, in __getitem__
    self.AddTemplate(template)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 187, in AddTemplate
    raise TemplateReadError('Could not load template %r' % template_path)
uweb3.templateparser.TemplateReadError: Could not load template '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 474, in __init__
    self._file_mtime = os.path.getmtime(self._file_name)
  File "/usr/lib/python3.6/genericpath.py", line 55, in getmtime
    return os.stat(filename).st_mtime
FileNotFoundError: [Errno 2] No such file or directory: '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 185, in AddTemplate
    self[name or location] = FileTemplate(template_path, parser=self)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 478, in __init__
    raise TemplateReadError('Cannot open: %r' % template_path)
uweb3.templateparser.TemplateReadError: Cannot open: '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 236, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/routes/login.py", line 35, in Login
    return self.parser.Parse('login.html')
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 204, in Parse
    return self[template].Parse(**replacements)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 163, in __getitem__
    self.AddTemplate(template)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 187, in AddTemplate
    raise TemplateReadError('Could not load template %r' % template_path)
uweb3.templateparser.TemplateReadError: Could not load template '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 474, in __init__
    self._file_mtime = os.path.getmtime(self._file_name)
  File "/usr/lib/python3.6/genericpath.py", line 55, in getmtime
    return os.stat(filename).st_mtime
FileNotFoundError: [Errno 2] No such file or directory: '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 185, in AddTemplate
    self[name or location] = FileTemplate(template_path, parser=self)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 478, in __init__
    raise TemplateReadError('Cannot open: %r' % template_path)
uweb3.templateparser.TemplateReadError: Cannot open: '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 236, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/routes/login.py", line 35, in Login
    return self.parser.Parse('login.html')
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 204, in Parse
    return self[template].Parse(**replacements)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 163, in __getitem__
    self.AddTemplate(template)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 187, in AddTemplate
    raise TemplateReadError('Could not load template %r' % template_path)
uweb3.templateparser.TemplateReadError: Could not load template '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 474, in __init__
    self._file_mtime = os.path.getmtime(self._file_name)
  File "/usr/lib/python3.6/genericpath.py", line 55, in getmtime
    return os.stat(filename).st_mtime
FileNotFoundError: [Errno 2] No such file or directory: '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 185, in AddTemplate
    self[name or location] = FileTemplate(template_path, parser=self)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 478, in __init__
    raise TemplateReadError('Cannot open: %r' % template_path)
uweb3.templateparser.TemplateReadError: Cannot open: '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 236, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/routes/login.py", line 35, in Login
    return self.parser.Parse('login.html')
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 204, in Parse
    return self[template].Parse(**replacements)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 163, in __getitem__
    self.AddTemplate(template)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 187, in AddTemplate
    raise TemplateReadError('Could not load template %r' % template_path)
uweb3.templateparser.TemplateReadError: Could not load template '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 474, in __init__
    self._file_mtime = os.path.getmtime(self._file_name)
  File "/usr/lib/python3.6/genericpath.py", line 55, in getmtime
    return os.stat(filename).st_mtime
FileNotFoundError: [Errno 2] No such file or directory: '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 185, in AddTemplate
    self[name or location] = FileTemplate(template_path, parser=self)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 478, in __init__
    raise TemplateReadError('Cannot open: %r' % template_path)
uweb3.templateparser.TemplateReadError: Cannot open: '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 236, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/routes/login.py", line 35, in Login
    return self.parser.Parse('login.html')
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 204, in Parse
    return self[template].Parse(**replacements)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 163, in __getitem__
    self.AddTemplate(template)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 187, in AddTemplate
    raise TemplateReadError('Could not load template %r' % template_path)
uweb3.templateparser.TemplateReadError: Could not load template '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 474, in __init__
    self._file_mtime = os.path.getmtime(self._file_name)
  File "/usr/lib/python3.6/genericpath.py", line 55, in getmtime
    return os.stat(filename).st_mtime
FileNotFoundError: [Errno 2] No such file or directory: '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 185, in AddTemplate
    self[name or location] = FileTemplate(template_path, parser=self)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 478, in __init__
    raise TemplateReadError('Cannot open: %r' % template_path)
uweb3.templateparser.TemplateReadError: Cannot open: '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 236, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/routes/login.py", line 35, in Login
    return self.parser.Parse('login.html')
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 204, in Parse
    return self[template].Parse(**replacements)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 163, in __getitem__
    self.AddTemplate(template)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 187, in AddTemplate
    raise TemplateReadError('Could not load template %r' % template_path)
uweb3.templateparser.TemplateReadError: Could not load template '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 474, in __init__
    self._file_mtime = os.path.getmtime(self._file_name)
  File "/usr/lib/python3.6/genericpath.py", line 55, in getmtime
    return os.stat(filename).st_mtime
FileNotFoundError: [Errno 2] No such file or directory: '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 185, in AddTemplate
    self[name or location] = FileTemplate(template_path, parser=self)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 478, in __init__
    raise TemplateReadError('Cannot open: %r' % template_path)
uweb3.templateparser.TemplateReadError: Cannot open: '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 236, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/routes/login.py", line 35, in Login
    return self.parser.Parse('login.html')
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 204, in Parse
    return self[template].Parse(**replacements)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 163, in __getitem__
    self.AddTemplate(template)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 187, in AddTemplate
    raise TemplateReadError('Could not load template %r' % template_path)
uweb3.templateparser.TemplateReadError: Could not load template '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 474, in __init__
    self._file_mtime = os.path.getmtime(self._file_name)
  File "/usr/lib/python3.6/genericpath.py", line 55, in getmtime
    return os.stat(filename).st_mtime
FileNotFoundError: [Errno 2] No such file or directory: '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 185, in AddTemplate
    self[name or location] = FileTemplate(template_path, parser=self)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 478, in __init__
    raise TemplateReadError('Cannot open: %r' % template_path)
uweb3.templateparser.TemplateReadError: Cannot open: '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 236, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/routes/login.py", line 35, in Login
    return self.parser.Parse('login.html')
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 204, in Parse
    return self[template].Parse(**replacements)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 163, in __getitem__
    self.AddTemplate(template)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 187, in AddTemplate
    raise TemplateReadError('Could not load template %r' % template_path)
uweb3.templateparser.TemplateReadError: Could not load template '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 474, in __init__
    self._file_mtime = os.path.getmtime(self._file_name)
  File "/usr/lib/python3.6/genericpath.py", line 55, in getmtime
    return os.stat(filename).st_mtime
FileNotFoundError: [Errno 2] No such file or directory: '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 185, in AddTemplate
    self[name or location] = FileTemplate(template_path, parser=self)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 478, in __init__
    raise TemplateReadError('Cannot open: %r' % template_path)
uweb3.templateparser.TemplateReadError: Cannot open: '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 236, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/routes/login.py", line 35, in Login
    return self.parser.Parse('login.html')
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 204, in Parse
    return self[template].Parse(**replacements)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 163, in __getitem__
    self.AddTemplate(template)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 187, in AddTemplate
    raise TemplateReadError('Could not load template %r' % template_path)
uweb3.templateparser.TemplateReadError: Could not load template '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 474, in __init__
    self._file_mtime = os.path.getmtime(self._file_name)
  File "/usr/lib/python3.6/genericpath.py", line 55, in getmtime
    return os.stat(filename).st_mtime
FileNotFoundError: [Errno 2] No such file or directory: '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 185, in AddTemplate
    self[name or location] = FileTemplate(template_path, parser=self)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 478, in __init__
    raise TemplateReadError('Cannot open: %r' % template_path)
uweb3.templateparser.TemplateReadError: Cannot open: '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 236, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/routes/login.py", line 35, in Login
    return self.parser.Parse('login.html')
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 204, in Parse
    return self[template].Parse(**replacements)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 163, in __getitem__
    self.AddTemplate(template)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 187, in AddTemplate
    raise TemplateReadError('Could not load template %r' % template_path)
uweb3.templateparser.TemplateReadError: Could not load template '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 474, in __init__
    self._file_mtime = os.path.getmtime(self._file_name)
  File "/usr/lib/python3.6/genericpath.py", line 55, in getmtime
    return os.stat(filename).st_mtime
FileNotFoundError: [Errno 2] No such file or directory: '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 185, in AddTemplate
    self[name or location] = FileTemplate(template_path, parser=self)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 478, in __init__
    raise TemplateReadError('Cannot open: %r' % template_path)
uweb3.templateparser.TemplateReadError: Cannot open: '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 236, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/routes/login.py", line 35, in Login
    return self.parser.Parse('login.html')
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 204, in Parse
    return self[template].Parse(**replacements)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 163, in __getitem__
    self.AddTemplate(template)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 187, in AddTemplate
    raise TemplateReadError('Could not load template %r' % template_path)
uweb3.templateparser.TemplateReadError: Could not load template '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 474, in __init__
    self._file_mtime = os.path.getmtime(self._file_name)
  File "/usr/lib/python3.6/genericpath.py", line 55, in getmtime
    return os.stat(filename).st_mtime
FileNotFoundError: [Errno 2] No such file or directory: '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 185, in AddTemplate
    self[name or location] = FileTemplate(template_path, parser=self)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 478, in __init__
    raise TemplateReadError('Cannot open: %r' % template_path)
uweb3.templateparser.TemplateReadError: Cannot open: '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 236, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/routes/login.py", line 35, in Login
    return self.parser.Parse('login.html')
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 204, in Parse
    return self[template].Parse(**replacements)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 163, in __getitem__
    self.AddTemplate(template)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 187, in AddTemplate
    raise TemplateReadError('Could not load template %r' % template_path)
uweb3.templateparser.TemplateReadError: Could not load template '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 474, in __init__
    self._file_mtime = os.path.getmtime(self._file_name)
  File "/usr/lib/python3.6/genericpath.py", line 55, in getmtime
    return os.stat(filename).st_mtime
FileNotFoundError: [Errno 2] No such file or directory: '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 185, in AddTemplate
    self[name or location] = FileTemplate(template_path, parser=self)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 478, in __init__
    raise TemplateReadError('Cannot open: %r' % template_path)
uweb3.templateparser.TemplateReadError: Cannot open: '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 236, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/routes/login.py", line 35, in Login
    return self.parser.Parse('login.html')
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 204, in Parse
    return self[template].Parse(**replacements)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 163, in __getitem__
    self.AddTemplate(template)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 187, in AddTemplate
    raise TemplateReadError('Could not load template %r' % template_path)
uweb3.templateparser.TemplateReadError: Could not load template '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 474, in __init__
    self._file_mtime = os.path.getmtime(self._file_name)
  File "/usr/lib/python3.6/genericpath.py", line 55, in getmtime
    return os.stat(filename).st_mtime
FileNotFoundError: [Errno 2] No such file or directory: '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 185, in AddTemplate
    self[name or location] = FileTemplate(template_path, parser=self)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 478, in __init__
    raise TemplateReadError('Cannot open: %r' % template_path)
uweb3.templateparser.TemplateReadError: Cannot open: '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 236, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/routes/login.py", line 35, in Login
    return self.parser.Parse('login.html')
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 204, in Parse
    return self[template].Parse(**replacements)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 163, in __getitem__
    self.AddTemplate(template)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 187, in AddTemplate
    raise TemplateReadError('Could not load template %r' % template_path)
uweb3.templateparser.TemplateReadError: Could not load template '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 474, in __init__
    self._file_mtime = os.path.getmtime(self._file_name)
  File "/usr/lib/python3.6/genericpath.py", line 55, in getmtime
    return os.stat(filename).st_mtime
FileNotFoundError: [Errno 2] No such file or directory: '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 185, in AddTemplate
    self[name or location] = FileTemplate(template_path, parser=self)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 478, in __init__
    raise TemplateReadError('Cannot open: %r' % template_path)
uweb3.templateparser.TemplateReadError: Cannot open: '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 236, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/routes/login.py", line 35, in Login
    return self.parser.Parse('login.html')
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 204, in Parse
    return self[template].Parse(**replacements)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 163, in __getitem__
    self.AddTemplate(template)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 187, in AddTemplate
    raise TemplateReadError('Could not load template %r' % template_path)
uweb3.templateparser.TemplateReadError: Could not load template '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 474, in __init__
    self._file_mtime = os.path.getmtime(self._file_name)
  File "/usr/lib/python3.6/genericpath.py", line 55, in getmtime
    return os.stat(filename).st_mtime
FileNotFoundError: [Errno 2] No such file or directory: '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 185, in AddTemplate
    self[name or location] = FileTemplate(template_path, parser=self)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 478, in __init__
    raise TemplateReadError('Cannot open: %r' % template_path)
uweb3.templateparser.TemplateReadError: Cannot open: '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 236, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/routes/login.py", line 35, in Login
    return self.parser.Parse('login.html')
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 204, in Parse
    return self[template].Parse(**replacements)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 163, in __getitem__
    self.AddTemplate(template)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 187, in AddTemplate
    raise TemplateReadError('Could not load template %r' % template_path)
uweb3.templateparser.TemplateReadError: Could not load template '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 474, in __init__
    self._file_mtime = os.path.getmtime(self._file_name)
  File "/usr/lib/python3.6/genericpath.py", line 55, in getmtime
    return os.stat(filename).st_mtime
FileNotFoundError: [Errno 2] No such file or directory: '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 185, in AddTemplate
    self[name or location] = FileTemplate(template_path, parser=self)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 478, in __init__
    raise TemplateReadError('Cannot open: %r' % template_path)
uweb3.templateparser.TemplateReadError: Cannot open: '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 236, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/routes/login.py", line 35, in Login
    return self.parser.Parse('login.html')
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 204, in Parse
    return self[template].Parse(**replacements)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 163, in __getitem__
    self.AddTemplate(template)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 187, in AddTemplate
    raise TemplateReadError('Could not load template %r' % template_path)
uweb3.templateparser.TemplateReadError: Could not load template '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 474, in __init__
    self._file_mtime = os.path.getmtime(self._file_name)
  File "/usr/lib/python3.6/genericpath.py", line 55, in getmtime
    return os.stat(filename).st_mtime
FileNotFoundError: [Errno 2] No such file or directory: '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 185, in AddTemplate
    self[name or location] = FileTemplate(template_path, parser=self)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 478, in __init__
    raise TemplateReadError('Cannot open: %r' % template_path)
uweb3.templateparser.TemplateReadError: Cannot open: '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 236, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/routes/login.py", line 35, in Login
    return self.parser.Parse('login.html')
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 204, in Parse
    return self[template].Parse(**replacements)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 163, in __getitem__
    self.AddTemplate(template)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 187, in AddTemplate
    raise TemplateReadError('Could not load template %r' % template_path)
uweb3.templateparser.TemplateReadError: Could not load template '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 474, in __init__
    self._file_mtime = os.path.getmtime(self._file_name)
  File "/usr/lib/python3.6/genericpath.py", line 55, in getmtime
    return os.stat(filename).st_mtime
FileNotFoundError: [Errno 2] No such file or directory: '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/404.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 185, in AddTemplate
    self[name or location] = FileTemplate(template_path, parser=self)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 478, in __init__
    raise TemplateReadError('Cannot open: %r' % template_path)
uweb3.templateparser.TemplateReadError: Cannot open: '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/404.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 236, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/base/pages.py", line 36, in FourOhFour
    return self.parser.Parse('404.html', path=path)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 204, in Parse
    return self[template].Parse(**replacements)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 163, in __getitem__
    self.AddTemplate(template)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 187, in AddTemplate
    raise TemplateReadError('Could not load template %r' % template_path)
uweb3.templateparser.TemplateReadError: Could not load template '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/404.html'
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 474, in __init__
    self._file_mtime = os.path.getmtime(self._file_name)
  File "/usr/lib/python3.6/genericpath.py", line 55, in getmtime
    return os.stat(filename).st_mtime
FileNotFoundError: [Errno 2] No such file or directory: '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/404.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 185, in AddTemplate
    self[name or location] = FileTemplate(template_path, parser=self)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 478, in __init__
    raise TemplateReadError('Cannot open: %r' % template_path)
uweb3.templateparser.TemplateReadError: Cannot open: '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/404.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 236, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/base/pages.py", line 36, in FourOhFour
    return self.parser.Parse('404.html', path=path)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 204, in Parse
    return self[template].Parse(**replacements)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 163, in __getitem__
    self.AddTemplate(template)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 187, in AddTemplate
    raise TemplateReadError('Could not load template %r' % template_path)
uweb3.templateparser.TemplateReadError: Could not load template '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/404.html'
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 474, in __init__
    self._file_mtime = os.path.getmtime(self._file_name)
  File "/usr/lib/python3.6/genericpath.py", line 55, in getmtime
    return os.stat(filename).st_mtime
FileNotFoundError: [Errno 2] No such file or directory: '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 185, in AddTemplate
    self[name or location] = FileTemplate(template_path, parser=self)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 478, in __init__
    raise TemplateReadError('Cannot open: %r' % template_path)
uweb3.templateparser.TemplateReadError: Cannot open: '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 236, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/routes/login.py", line 35, in Login
    return self.parser.Parse('login.html')
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 204, in Parse
    return self[template].Parse(**replacements)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 163, in __getitem__
    self.AddTemplate(template)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 187, in AddTemplate
    raise TemplateReadError('Could not load template %r' % template_path)
uweb3.templateparser.TemplateReadError: Could not load template '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 474, in __init__
    self._file_mtime = os.path.getmtime(self._file_name)
  File "/usr/lib/python3.6/genericpath.py", line 55, in getmtime
    return os.stat(filename).st_mtime
FileNotFoundError: [Errno 2] No such file or directory: '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/404.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 185, in AddTemplate
    self[name or location] = FileTemplate(template_path, parser=self)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 478, in __init__
    raise TemplateReadError('Cannot open: %r' % template_path)
uweb3.templateparser.TemplateReadError: Cannot open: '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/404.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 236, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/base/pages.py", line 36, in FourOhFour
    return self.parser.Parse('404.html', path=path)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 204, in Parse
    return self[template].Parse(**replacements)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 163, in __getitem__
    self.AddTemplate(template)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 187, in AddTemplate
    raise TemplateReadError('Could not load template %r' % template_path)
uweb3.templateparser.TemplateReadError: Could not load template '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/404.html'
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 474, in __init__
    self._file_mtime = os.path.getmtime(self._file_name)
  File "/usr/lib/python3.6/genericpath.py", line 55, in getmtime
    return os.stat(filename).st_mtime
FileNotFoundError: [Errno 2] No such file or directory: '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/404.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 185, in AddTemplate
    self[name or location] = FileTemplate(template_path, parser=self)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 478, in __init__
    raise TemplateReadError('Cannot open: %r' % template_path)
uweb3.templateparser.TemplateReadError: Cannot open: '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/404.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 236, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/base/pages.py", line 36, in FourOhFour
    return self.parser.Parse('404.html', path=path)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 204, in Parse
    return self[template].Parse(**replacements)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 163, in __getitem__
    self.AddTemplate(template)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 187, in AddTemplate
    raise TemplateReadError('Could not load template %r' % template_path)
uweb3.templateparser.TemplateReadError: Could not load template '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/404.html'
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 474, in __init__
    self._file_mtime = os.path.getmtime(self._file_name)
  File "/usr/lib/python3.6/genericpath.py", line 55, in getmtime
    return os.stat(filename).st_mtime
FileNotFoundError: [Errno 2] No such file or directory: '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 185, in AddTemplate
    self[name or location] = FileTemplate(template_path, parser=self)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 478, in __init__
    raise TemplateReadError('Cannot open: %r' % template_path)
uweb3.templateparser.TemplateReadError: Cannot open: '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 236, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/routes/login.py", line 35, in Login
    return self.parser.Parse('login.html')
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 204, in Parse
    return self[template].Parse(**replacements)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 163, in __getitem__
    self.AddTemplate(template)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 187, in AddTemplate
    raise TemplateReadError('Could not load template %r' % template_path)
uweb3.templateparser.TemplateReadError: Could not load template '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 474, in __init__
    self._file_mtime = os.path.getmtime(self._file_name)
  File "/usr/lib/python3.6/genericpath.py", line 55, in getmtime
    return os.stat(filename).st_mtime
FileNotFoundError: [Errno 2] No such file or directory: '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 185, in AddTemplate
    self[name or location] = FileTemplate(template_path, parser=self)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 478, in __init__
    raise TemplateReadError('Cannot open: %r' % template_path)
uweb3.templateparser.TemplateReadError: Cannot open: '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 236, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/routes/login.py", line 35, in Login
    return self.parser.Parse('login.html')
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 204, in Parse
    return self[template].Parse(**replacements)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 163, in __getitem__
    self.AddTemplate(template)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 187, in AddTemplate
    raise TemplateReadError('Could not load template %r' % template_path)
uweb3.templateparser.TemplateReadError: Could not load template '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 474, in __init__
    self._file_mtime = os.path.getmtime(self._file_name)
  File "/usr/lib/python3.6/genericpath.py", line 55, in getmtime
    return os.stat(filename).st_mtime
FileNotFoundError: [Errno 2] No such file or directory: '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 185, in AddTemplate
    self[name or location] = FileTemplate(template_path, parser=self)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 478, in __init__
    raise TemplateReadError('Cannot open: %r' % template_path)
uweb3.templateparser.TemplateReadError: Cannot open: '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 236, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/routes/login.py", line 35, in Login
    return self.parser.Parse('login.html')
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 204, in Parse
    return self[template].Parse(**replacements)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 163, in __getitem__
    self.AddTemplate(template)
  File "/home/stef/devel/uweb3/uweb3/templateparser.py", line 187, in AddTemplate
    raise TemplateReadError('Could not load template %r' % template_path)
uweb3.templateparser.TemplateReadError: Could not load template '/home/stef/devel/uweb3/uweb3/scaffold/routes/templates/login.html'
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 236, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/routes/login.py", line 17, in Login
    raise Exception("test")
Exception: test
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 236, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/routes/login.py", line 17, in Login
    raise Exception("test")
Exception: test
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 236, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/routes/login.py", line 17, in Login
    raise Exception("test")
Exception: test
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 235, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/routes/login.py", line 19, in Login
    raise Exception('test')
Exception: test
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 235, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/routes/login.py", line 19, in Login
    raise Exception('test')
Exception: test
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 235, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/routes/login.py", line 19, in Login
    raise Exception('test')
Exception: test
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 235, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/routes/login.py", line 19, in Login
    raise Exception('test')
Exception: test
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 235, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/routes/login.py", line 19, in Login
    raise Exception('test')
Exception: test
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 235, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/routes/login.py", line 19, in Login
    raise Exception('test')
Exception: test
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 235, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/routes/login.py", line 19, in Login
    raise Exception('test')
Exception: test
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 235, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/routes/login.py", line 19, in Login
    raise Exception('test')
Exception: test
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 235, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/routes/login.py", line 19, in Login
    raise Exception('test')
Exception: test
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 235, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/routes/login.py", line 19, in Login
    raise Exception('test')
Exception: test
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 235, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/routes/login.py", line 19, in Login
    if self.req.method == 'POST':
Exception: test
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 235, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/routes/login.py", line 19, in Login
    if self.req.method == 'POST':
Exception: test
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 235, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/routes/login.py", line 19, in Login
    if self.req.method == 'POST':
Exception: test
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 235, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/routes/login.py", line 19, in Login
    if self.req.method == 'POST':
Exception: test
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 235, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/routes/login.py", line 19, in Login
    if self.req.method == 'POST':
Exception: test
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 235, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/routes/login.py", line 19, in Login
    raise Exception()
Exception
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 235, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/routes/login.py", line 19, in Login
    raise Exception()
Exception
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 235, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/routes/login.py", line 19, in Login
    raise Exception()
Exception
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 235, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/routes/login.py", line 19, in Login
    raise Exception()
Exception
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 235, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/routes/login.py", line 19, in Login
    raise Exception()
Exception
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 235, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/routes/login.py", line 19, in Login
    raise Exception()
Exception
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 235, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/routes/login.py", line 19, in Login
    raise Exception()
Exception
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 235, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/routes/login.py", line 19, in Login
    raise Exception()
Exception
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 235, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/routes/login.py", line 19, in Login
    raise Exception()
Exception
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 235, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/routes/login.py", line 19, in Login
    raise Exception()
Exception
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 235, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/routes/login.py", line 19, in Login
    raise Exception()
Exception
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 235, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/routes/login.py", line 19, in Login
    raise Exception()
Exception
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 235, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/routes/login.py", line 19, in Login
    raise Exception()
Exception
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 235, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/routes/login.py", line 19, in Login
    raise Exception()
Exception
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 235, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/routes/login.py", line 19, in Login
    raise Exception()
Exception
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 235, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/routes/login.py", line 19, in Login
    raise Exception()
Exception
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 235, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/routes/login.py", line 19, in Login
    raise Exception()
Exception
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 235, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/routes/login.py", line 19, in Login
    raise Exception()
Exception
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 235, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/routes/login.py", line 19, in Login
    raise Exception()
Exception
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 235, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/routes/login.py", line 19, in Login
    raise Exception()
Exception
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 235, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/routes/login.py", line 19, in Login
    raise Exception()
Exception
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 235, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/routes/login.py", line 19, in Login
    raise Exception()
Exception
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 235, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/routes/login.py", line 19, in Login
    raise Exception()
Exception
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 235, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/routes/login.py", line 19, in Login
    raise Exception()
Exception
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 235, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/routes/login.py", line 19, in Login
    raise Exception()
Exception
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 235, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/routes/login.py", line 19, in Login
    raise Exception()
Exception
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 235, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/routes/login.py", line 19, in Login
    raise Exception()
Exception
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 235, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/routes/login.py", line 19, in Login
    raise Exception()
Exception
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 235, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/routes/login.py", line 19, in Login
    raise Exception()
Exception
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 235, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/routes/login.py", line 17, in Login
    raise Exception('test')
Exception: test
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3-venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
    cursor, statement, parameters, context
  File "/home/stef/devel/uweb3/uweb3-venv/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 588, in do_execute
    cursor.execute(statement, parameters)
  File "/home/stef/devel/uweb3/uweb3-venv/lib/python3.6/site-packages/MySQLdb/cursors.py", line 209, in execute
    res = self._query(query)
  File "/home/stef/devel/uweb3/uweb3-venv/lib/python3.6/site-packages/MySQLdb/cursors.py", line 315, in _query
    db.query(q)
  File "/home/stef/devel/uweb3/uweb3-venv/lib/python3.6/site-packages/MySQLdb/connections.py", line 239, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.IntegrityError: (1062, "Duplicate entry 'hello' for key 'username'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 235, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/routes/sqlalchemy.py", line 83, in Sqlalchemy
    print(User.Create(self.session, {'username': 'hello', 'password': 'test', 'authorid': 1}))
  File "/home/stef/devel/uweb3/uweb3/model.py", line 1543, in Create
    return cls(session, record)
  File "<string>", line 4, in __init__
  File "/home/stef/devel/uweb3/uweb3-venv/lib/python3.6/site-packages/sqlalchemy/orm/state.py", line 433, in _initialize_instance
    manager.dispatch.init_failure(self, args, kwargs)
  File "/home/stef/devel/uweb3/uweb3-venv/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "/home/stef/devel/uweb3/uweb3-venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/home/stef/devel/uweb3/uweb3-venv/lib/python3.6/site-packages/sqlalchemy/orm/state.py", line 430, in _initialize_instance
    return manager.original_init(*mixed[1:], **kwargs)
  File "/home/stef/devel/uweb3/uweb3/scaffold/routes/sqlalchemy.py", line 26, in __init__
    super(User, self).__init__(*args, **kwargs)
  File "/home/stef/devel/uweb3/uweb3/model.py", line 1302, in __init__
    self._BuildClassFromRecord(record)
  File "/home/stef/devel/uweb3/uweb3/model.py", line 1317, in _BuildClassFromRecord
    self.session.commit()
  File "/home/stef/devel/uweb3/uweb3-venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1036, in commit
    self.transaction.commit()
  File "/home/stef/devel/uweb3/uweb3-venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 503, in commit
    self._prepare_impl()
  File "/home/stef/devel/uweb3/uweb3-venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 482, in _prepare_impl
    self.session.flush()
  File "/home/stef/devel/uweb3/uweb3-venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2496, in flush
    self._flush(objects)
  File "/home/stef/devel/uweb3/uweb3-venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2637, in _flush
    transaction.rollback(_capture_exception=True)
  File "/home/stef/devel/uweb3/uweb3-venv/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "/home/stef/devel/uweb3/uweb3-venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/home/stef/devel/uweb3/uweb3-venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2597, in _flush
    flush_context.execute()
  File "/home/stef/devel/uweb3/uweb3-venv/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 422, in execute
    rec.execute(self)
  File "/home/stef/devel/uweb3/uweb3-venv/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 589, in execute
    uow,
  File "/home/stef/devel/uweb3/uweb3-venv/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 245, in save_obj
    insert,
  File "/home/stef/devel/uweb3/uweb3-venv/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 1136, in _emit_insert_statements
    statement, params
  File "/home/stef/devel/uweb3/uweb3-venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 984, in execute
    return meth(self, multiparams, params)
  File "/home/stef/devel/uweb3/uweb3-venv/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 293, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/stef/devel/uweb3/uweb3-venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1103, in _execute_clauseelement
    distilled_params,
  File "/home/stef/devel/uweb3/uweb3-venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1288, in _execute_context
    e, statement, parameters, cursor, context
  File "/home/stef/devel/uweb3/uweb3-venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1482, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/stef/devel/uweb3/uweb3-venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/home/stef/devel/uweb3/uweb3-venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
    cursor, statement, parameters, context
  File "/home/stef/devel/uweb3/uweb3-venv/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 588, in do_execute
    cursor.execute(statement, parameters)
  File "/home/stef/devel/uweb3/uweb3-venv/lib/python3.6/site-packages/MySQLdb/cursors.py", line 209, in execute
    res = self._query(query)
  File "/home/stef/devel/uweb3/uweb3-venv/lib/python3.6/site-packages/MySQLdb/cursors.py", line 315, in _query
    db.query(q)
  File "/home/stef/devel/uweb3/uweb3-venv/lib/python3.6/site-packages/MySQLdb/connections.py", line 239, in query
    _mysql.connection.query(self, query)
sqlalchemy.exc.IntegrityError: (MySQLdb._exceptions.IntegrityError) (1062, "Duplicate entry 'hello' for key 'username'")
[SQL: INSERT INTO alchemy_users (username, password, authorid) VALUES (%s, %s, %s)]
[parameters: ('hello', 'test', 1)]
(Background on this error at: http://sqlalche.me/e/gkpj)
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3-venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
    cursor, statement, parameters, context
  File "/home/stef/devel/uweb3/uweb3-venv/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 588, in do_execute
    cursor.execute(statement, parameters)
  File "/home/stef/devel/uweb3/uweb3-venv/lib/python3.6/site-packages/MySQLdb/cursors.py", line 209, in execute
    res = self._query(query)
  File "/home/stef/devel/uweb3/uweb3-venv/lib/python3.6/site-packages/MySQLdb/cursors.py", line 315, in _query
    db.query(q)
  File "/home/stef/devel/uweb3/uweb3-venv/lib/python3.6/site-packages/MySQLdb/connections.py", line 239, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.IntegrityError: (1062, "Duplicate entry 'hello' for key 'username'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 235, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/routes/sqlalchemy.py", line 83, in Sqlalchemy
    print(User.Create(self.session, {'username': 'hello', 'password': 'test', 'authorid': 1}))
  File "/home/stef/devel/uweb3/uweb3/model.py", line 1543, in Create
    return cls(session, record)
  File "<string>", line 4, in __init__
  File "/home/stef/devel/uweb3/uweb3-venv/lib/python3.6/site-packages/sqlalchemy/orm/state.py", line 433, in _initialize_instance
    manager.dispatch.init_failure(self, args, kwargs)
  File "/home/stef/devel/uweb3/uweb3-venv/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "/home/stef/devel/uweb3/uweb3-venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/home/stef/devel/uweb3/uweb3-venv/lib/python3.6/site-packages/sqlalchemy/orm/state.py", line 430, in _initialize_instance
    return manager.original_init(*mixed[1:], **kwargs)
  File "/home/stef/devel/uweb3/uweb3/scaffold/routes/sqlalchemy.py", line 26, in __init__
    super(User, self).__init__(*args, **kwargs)
  File "/home/stef/devel/uweb3/uweb3/model.py", line 1302, in __init__
    self._BuildClassFromRecord(record)
  File "/home/stef/devel/uweb3/uweb3/model.py", line 1317, in _BuildClassFromRecord
    self.session.commit()
  File "/home/stef/devel/uweb3/uweb3-venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1036, in commit
    self.transaction.commit()
  File "/home/stef/devel/uweb3/uweb3-venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 503, in commit
    self._prepare_impl()
  File "/home/stef/devel/uweb3/uweb3-venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 482, in _prepare_impl
    self.session.flush()
  File "/home/stef/devel/uweb3/uweb3-venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2496, in flush
    self._flush(objects)
  File "/home/stef/devel/uweb3/uweb3-venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2637, in _flush
    transaction.rollback(_capture_exception=True)
  File "/home/stef/devel/uweb3/uweb3-venv/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "/home/stef/devel/uweb3/uweb3-venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/home/stef/devel/uweb3/uweb3-venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2597, in _flush
    flush_context.execute()
  File "/home/stef/devel/uweb3/uweb3-venv/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 422, in execute
    rec.execute(self)
  File "/home/stef/devel/uweb3/uweb3-venv/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 589, in execute
    uow,
  File "/home/stef/devel/uweb3/uweb3-venv/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 245, in save_obj
    insert,
  File "/home/stef/devel/uweb3/uweb3-venv/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 1136, in _emit_insert_statements
    statement, params
  File "/home/stef/devel/uweb3/uweb3-venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 984, in execute
    return meth(self, multiparams, params)
  File "/home/stef/devel/uweb3/uweb3-venv/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 293, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/stef/devel/uweb3/uweb3-venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1103, in _execute_clauseelement
    distilled_params,
  File "/home/stef/devel/uweb3/uweb3-venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1288, in _execute_context
    e, statement, parameters, cursor, context
  File "/home/stef/devel/uweb3/uweb3-venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1482, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/stef/devel/uweb3/uweb3-venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/home/stef/devel/uweb3/uweb3-venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
    cursor, statement, parameters, context
  File "/home/stef/devel/uweb3/uweb3-venv/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 588, in do_execute
    cursor.execute(statement, parameters)
  File "/home/stef/devel/uweb3/uweb3-venv/lib/python3.6/site-packages/MySQLdb/cursors.py", line 209, in execute
    res = self._query(query)
  File "/home/stef/devel/uweb3/uweb3-venv/lib/python3.6/site-packages/MySQLdb/cursors.py", line 315, in _query
    db.query(q)
  File "/home/stef/devel/uweb3/uweb3-venv/lib/python3.6/site-packages/MySQLdb/connections.py", line 239, in query
    _mysql.connection.query(self, query)
sqlalchemy.exc.IntegrityError: (MySQLdb._exceptions.IntegrityError) (1062, "Duplicate entry 'hello' for key 'username'")
[SQL: INSERT INTO alchemy_users (username, password, authorid) VALUES (%s, %s, %s)]
[parameters: ('hello', 'test', 1)]
(Background on this error at: http://sqlalche.me/e/gkpj)
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3-venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
    cursor, statement, parameters, context
  File "/home/stef/devel/uweb3/uweb3-venv/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 588, in do_execute
    cursor.execute(statement, parameters)
  File "/home/stef/devel/uweb3/uweb3-venv/lib/python3.6/site-packages/MySQLdb/cursors.py", line 209, in execute
    res = self._query(query)
  File "/home/stef/devel/uweb3/uweb3-venv/lib/python3.6/site-packages/MySQLdb/cursors.py", line 315, in _query
    db.query(q)
  File "/home/stef/devel/uweb3/uweb3-venv/lib/python3.6/site-packages/MySQLdb/connections.py", line 239, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.IntegrityError: (1062, "Duplicate entry 'hello' for key 'username'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 235, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/routes/sqlalchemy.py", line 83, in Sqlalchemy
    print(User.Create(self.session, {'username': 'hello', 'password': 'test', 'authorid': 1}))
  File "/home/stef/devel/uweb3/uweb3/model.py", line 1543, in Create
    return cls(session, record)
  File "<string>", line 4, in __init__
  File "/home/stef/devel/uweb3/uweb3-venv/lib/python3.6/site-packages/sqlalchemy/orm/state.py", line 433, in _initialize_instance
    manager.dispatch.init_failure(self, args, kwargs)
  File "/home/stef/devel/uweb3/uweb3-venv/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "/home/stef/devel/uweb3/uweb3-venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/home/stef/devel/uweb3/uweb3-venv/lib/python3.6/site-packages/sqlalchemy/orm/state.py", line 430, in _initialize_instance
    return manager.original_init(*mixed[1:], **kwargs)
  File "/home/stef/devel/uweb3/uweb3/scaffold/routes/sqlalchemy.py", line 26, in __init__
    super(User, self).__init__(*args, **kwargs)
  File "/home/stef/devel/uweb3/uweb3/model.py", line 1302, in __init__
    self._BuildClassFromRecord(record)
  File "/home/stef/devel/uweb3/uweb3/model.py", line 1317, in _BuildClassFromRecord
    self.session.commit()
  File "/home/stef/devel/uweb3/uweb3-venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1036, in commit
    self.transaction.commit()
  File "/home/stef/devel/uweb3/uweb3-venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 503, in commit
    self._prepare_impl()
  File "/home/stef/devel/uweb3/uweb3-venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 482, in _prepare_impl
    self.session.flush()
  File "/home/stef/devel/uweb3/uweb3-venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2496, in flush
    self._flush(objects)
  File "/home/stef/devel/uweb3/uweb3-venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2637, in _flush
    transaction.rollback(_capture_exception=True)
  File "/home/stef/devel/uweb3/uweb3-venv/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "/home/stef/devel/uweb3/uweb3-venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/home/stef/devel/uweb3/uweb3-venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2597, in _flush
    flush_context.execute()
  File "/home/stef/devel/uweb3/uweb3-venv/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 422, in execute
    rec.execute(self)
  File "/home/stef/devel/uweb3/uweb3-venv/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 589, in execute
    uow,
  File "/home/stef/devel/uweb3/uweb3-venv/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 245, in save_obj
    insert,
  File "/home/stef/devel/uweb3/uweb3-venv/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 1136, in _emit_insert_statements
    statement, params
  File "/home/stef/devel/uweb3/uweb3-venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 984, in execute
    return meth(self, multiparams, params)
  File "/home/stef/devel/uweb3/uweb3-venv/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 293, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/stef/devel/uweb3/uweb3-venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1103, in _execute_clauseelement
    distilled_params,
  File "/home/stef/devel/uweb3/uweb3-venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1288, in _execute_context
    e, statement, parameters, cursor, context
  File "/home/stef/devel/uweb3/uweb3-venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1482, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/stef/devel/uweb3/uweb3-venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/home/stef/devel/uweb3/uweb3-venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
    cursor, statement, parameters, context
  File "/home/stef/devel/uweb3/uweb3-venv/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 588, in do_execute
    cursor.execute(statement, parameters)
  File "/home/stef/devel/uweb3/uweb3-venv/lib/python3.6/site-packages/MySQLdb/cursors.py", line 209, in execute
    res = self._query(query)
  File "/home/stef/devel/uweb3/uweb3-venv/lib/python3.6/site-packages/MySQLdb/cursors.py", line 315, in _query
    db.query(q)
  File "/home/stef/devel/uweb3/uweb3-venv/lib/python3.6/site-packages/MySQLdb/connections.py", line 239, in query
    _mysql.connection.query(self, query)
sqlalchemy.exc.IntegrityError: (MySQLdb._exceptions.IntegrityError) (1062, "Duplicate entry 'hello' for key 'username'")
[SQL: INSERT INTO alchemy_users (username, password, authorid) VALUES (%s, %s, %s)]
[parameters: ('hello', 'test', 1)]
(Background on this error at: http://sqlalche.me/e/gkpj)
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 235, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/routes/sqlalchemy.py", line 78, in Sqlalchemy
    raise Exception()
Exception
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 235, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/routes/sqlalchemy.py", line 78, in Sqlalchemy
    raise Exception()
Exception
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 235, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/routes/sqlalchemy.py", line 78, in Sqlalchemy
    raise Exception()
Exception
UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 235, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/routes/sqlalchemy.py", line 78, in Sqlalchemy
    raise Exception()
Exception
