ERROR: 
Traceback (most recent call last):
  File "/home/stef/devel/uweb3/uweb3/__init__.py", line 141, in get_response
    return getattr(page_maker, method)(*args)
  File "/home/stef/devel/uweb3/uweb3/scaffold/routes/login.py", line 15, in Login
    raise Exception("TEST")
Exception: TEST
